// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/finance.proto

package financePb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletRequest) Reset() {
	*x = WalletRequest{}
	mi := &file_proto_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletRequest) ProtoMessage() {}

func (x *WalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletRequest.ProtoReflect.Descriptor instead.
func (*WalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_proto_rawDescGZIP(), []int{0}
}

func (x *WalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentsRequest) Reset() {
	*x = PaymentsRequest{}
	mi := &file_proto_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentsRequest) ProtoMessage() {}

func (x *PaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentsRequest.ProtoReflect.Descriptor instead.
func (*PaymentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WalletResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance   float64                `protobuf:"fixed64,4,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_proto_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_proto_rawDescGZIP(), []int{2}
}

func (x *WalletResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WalletResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WalletResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *WalletResponse) GetPendingBalance() float64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *WalletResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WalletResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WalletResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaymentItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId      string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionType    string                 `protobuf:"bytes,4,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	XenditPaymentReqId string                 `protobuf:"bytes,5,opt,name=xendit_payment_req_id,json=xenditPaymentReqId,proto3" json:"xendit_payment_req_id,omitempty"`
	Amount             float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency           string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	MethodType         string                 `protobuf:"bytes,8,opt,name=method_type,json=methodType,proto3" json:"method_type,omitempty"`
	ChannelCode        string                 `protobuf:"bytes,9,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	PaymentActionInfo  string                 `protobuf:"bytes,10,opt,name=payment_action_info,json=paymentActionInfo,proto3" json:"payment_action_info,omitempty"`
	Status             string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PaidAt             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PaymentItem) Reset() {
	*x = PaymentItem{}
	mi := &file_proto_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentItem) ProtoMessage() {}

func (x *PaymentItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentItem.ProtoReflect.Descriptor instead.
func (*PaymentItem) Descriptor() ([]byte, []int) {
	return file_proto_finance_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentItem) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentItem) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *PaymentItem) GetXenditPaymentReqId() string {
	if x != nil {
		return x.XenditPaymentReqId
	}
	return ""
}

func (x *PaymentItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentItem) GetMethodType() string {
	if x != nil {
		return x.MethodType
	}
	return ""
}

func (x *PaymentItem) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *PaymentItem) GetPaymentActionInfo() string {
	if x != nil {
		return x.PaymentActionInfo
	}
	return ""
}

func (x *PaymentItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentItem) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PaymentItem) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *PaymentItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentItem         `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentsResponse) Reset() {
	*x = PaymentsResponse{}
	mi := &file_proto_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentsResponse) ProtoMessage() {}

func (x *PaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentsResponse.ProtoReflect.Descriptor instead.
func (*PaymentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentsResponse) GetPayments() []*PaymentItem {
	if x != nil {
		return x.Payments
	}
	return nil
}

var File_proto_finance_proto protoreflect.FileDescriptor

const file_proto_finance_proto_rawDesc = "" +
	"\n" +
	"\x13proto/finance.proto\x12\afinance\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\rWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0fPaymentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb9\x02\n" +
	"\x0eWalletResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x11available_balance\x18\x03 \x01(\x01R\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\x04 \x01(\x01R\x0ependingBalance\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe1\x04\n" +
	"\vPaymentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12)\n" +
	"\x10transaction_type\x18\x04 \x01(\tR\x0ftransactionType\x121\n" +
	"\x15xendit_payment_req_id\x18\x05 \x01(\tR\x12xenditPaymentReqId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1f\n" +
	"\vmethod_type\x18\b \x01(\tR\n" +
	"methodType\x12!\n" +
	"\fchannel_code\x18\t \x01(\tR\vchannelCode\x12.\n" +
	"\x13payment_action_info\x18\n" +
	" \x01(\tR\x11paymentActionInfo\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x123\n" +
	"\apaid_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"D\n" +
	"\x10PaymentsResponse\x120\n" +
	"\bpayments\x18\x01 \x03(\v2\x14.finance.PaymentItemR\bpayments2\x92\x01\n" +
	"\x0eFinanceService\x12<\n" +
	"\tGetWallet\x12\x16.finance.WalletRequest\x1a\x17.finance.WalletResponse\x12B\n" +
	"\vGetPayments\x12\x18.finance.PaymentsRequest\x1a\x19.finance.PaymentsResponseB\x11Z\x0fproto/financePbb\x06proto3"

var (
	file_proto_finance_proto_rawDescOnce sync.Once
	file_proto_finance_proto_rawDescData []byte
)

func file_proto_finance_proto_rawDescGZIP() []byte {
	file_proto_finance_proto_rawDescOnce.Do(func() {
		file_proto_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_finance_proto_rawDesc), len(file_proto_finance_proto_rawDesc)))
	})
	return file_proto_finance_proto_rawDescData
}

var file_proto_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_finance_proto_goTypes = []any{
	(*WalletRequest)(nil),         // 0: finance.WalletRequest
	(*PaymentsRequest)(nil),       // 1: finance.PaymentsRequest
	(*WalletResponse)(nil),        // 2: finance.WalletResponse
	(*PaymentItem)(nil),           // 3: finance.PaymentItem
	(*PaymentsResponse)(nil),      // 4: finance.PaymentsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_finance_proto_depIdxs = []int32{
	5, // 0: finance.WalletResponse.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: finance.WalletResponse.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: finance.PaymentItem.expires_at:type_name -> google.protobuf.Timestamp
	5, // 3: finance.PaymentItem.paid_at:type_name -> google.protobuf.Timestamp
	5, // 4: finance.PaymentItem.created_at:type_name -> google.protobuf.Timestamp
	5, // 5: finance.PaymentItem.updated_at:type_name -> google.protobuf.Timestamp
	3, // 6: finance.PaymentsResponse.payments:type_name -> finance.PaymentItem
	0, // 7: finance.FinanceService.GetWallet:input_type -> finance.WalletRequest
	1, // 8: finance.FinanceService.GetPayments:input_type -> finance.PaymentsRequest
	2, // 9: finance.FinanceService.GetWallet:output_type -> finance.WalletResponse
	4, // 10: finance.FinanceService.GetPayments:output_type -> finance.PaymentsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_finance_proto_init() }
func file_proto_finance_proto_init() {
	if File_proto_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_finance_proto_rawDesc), len(file_proto_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finance_proto_goTypes,
		DependencyIndexes: file_proto_finance_proto_depIdxs,
		MessageInfos:      file_proto_finance_proto_msgTypes,
	}.Build()
	File_proto_finance_proto = out.File
	file_proto_finance_proto_goTypes = nil
	file_proto_finance_proto_depIdxs = nil
}
