name: g-nexa
services:
  # ------------------------------------
  # 1. DATABASE: POSTGRESQL
  # ------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: g-nexa-postgres
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_DB: postgres
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    networks:
      - g-nexa-network

  # ------------------------------------
  # 1.5 CACHE: REDIS
  # ------------------------------------
  redis:
    image: redis:7-alpine
    container_name: g-nexa-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - g-nexa-network

  # ------------------------------------
  # 2. DATABASE: MONGODB
  # ------------------------------------
  mongo:
    image: mongo:8.0.0
    container_name: g-nexa-mongo
    restart: always
    env_file: ../.env
    ports:
      - "28017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - g-nexa-network

  # ------------------------------------
  # 2. Message Broker Kafka
  # ------------------------------------
  kafka:
    image: apache/kafka:3.7.0
    container_name: g-nexa-kafka
    user: root
    ports:
      - "9092:9092" # Port untuk akses dari laptop (Host / Luar Docker)
      - "29092:29092" # Port untuk akses antar container di dalam Docker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Konfigurasi Listener (Sangat penting agar bisa diakses dari Host & Container)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # Pengaturan Wajib KRaft untuk 1 Node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # UUID unik untuk inisialisasi cluster otomatis
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka_data:/tmp/kafka-logs
    networks:
      - g-nexa-network

  # ------------------------------------
  # 2.Kafka UI
  # ------------------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: g-nexa-kafka-ui
    ports:
      - "8088:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=GNEXA-Local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - g-nexa-network
  # ------------------------------------
  # 3. USER SERVICE (Bun + Hot Reload)
  # ------------------------------------
  user-service:
    build:
      context: ../apps/services/users
      target: development
    container_name: g-nexa-user-service
    restart: always
    ports:
      # - "8081:8081"
      - "50052:50052"

    env_file:
      - ../apps/services/users/.env
    environment:
      - PORT=8081

    volumes:
      - ../apps/services/users:/app # Sync Code
      - /app/node_modules # Protect node_modules

    command: /bin/sh -c "bunx prisma migrate dev --name auto_dev && bun run dev"

    depends_on:
      - postgres
      - kafka
      - redis
    networks:
      - g-nexa-network

  # ------------------------------------
  # 4. PRODUCT SERVICE (Go + Hot Reload)
  # ------------------------------------
  product-service:
    build:
      context: ../apps/services/product
      target: development # Pastikan ini development
    container_name: g-nexa-product-service
    restart: always
    ports:
      - "50051:50051"
    # - "8082:8082"

    env_file:
      - ../apps/services/product/files/config/.env
    environment:
      - PORT=8082

    volumes:
      - ../apps/services/product:/app # Sync Code
      - /app/tmp # Folder temp Air

    depends_on:
      - mongo
      - kafka
      - redis
    networks:
      - g-nexa-network

  # ------------------------------------
  # 5. MEDIA SERVICE (Go + Hot Reload)
  # ------------------------------------
  media-service:
    build:
      context: ../apps/services/media
      target: development # Pastikan ini development
    container_name: g-nexa-media-service
    restart: always
    # ports:
    # - "8083:8083"

    env_file:
      - ../apps/services/media/files/config/.env
    environment:
      - PORT=8083

    volumes:
      - ../apps/services/media:/app # Sync Code
      - /app/tmp # Folder temp Air

    depends_on:
      - postgres
      - kafka
    networks:
      - g-nexa-network

  # ------------------------------------
  # 6. ORDER SERVICE
  # ------------------------------------
  order-service:
    build:
      context: ../apps/services/order
      target: development
    container_name: g-nexa-order-service
    restart: always
    # ports:
    # - "8084:8084"
    env_file:
      - ../apps/services/order/.env
    volumes:
      - ../apps/services/order:/app
      - /app/node_modules
    command: /bin/sh -c "npx prisma migrate dev --name auto_dev && npm run start:dev"
    depends_on:
      - postgres
      - kafka
      - redis
    networks:
      - g-nexa-network

  # ------------------------------------
  # 6. FINANCE SERVICE
  # ------------------------------------
  finance-service:
    build:
      context: ../apps/services/finance
      target: development
    container_name: g-nexa-finance-service
    ports:
      - "50053:50053"
    env_file:
      - ../apps/services/finance/files/config/.env
    volumes:
      - ../apps/services/finance:/app
      - /app/tmp
    depends_on:
      - postgres
      - kafka
      - redis
    networks:
      - g-nexa-network
  # ------------------------------------
  # 7. WEB MARKET PLACE
  # ------------------------------------
  web-market-place:
    build:
      context: ../apps/web/public/market-place
      target: development
    container_name: g-nexa-web-market-place
    restart: always
    ports:
      - "3000:3000"

    env_file:
      - ../apps/web/public/market-place/.env
    environment:
      - PORT=3000
    volumes:
      - ../apps/web/public/market-place:/app # 1. Sync Source Code (Hot Reload)
      - /app/node_modules # 2. Cegah node_modules laptop menimpa container
      - /app/.next # 3. [PENTING] Simpan cache build Next.js di dalam container saja

    depends_on:
      - user-service
      - product-service

    networks:
      - g-nexa-network

  kong:
    image: kong:latest
    container_name: g-nexa-kong-gateway
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yaml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
    ports:
      - "8000:8000"
      # - "8001:8001" # PORT ADMIN (Opsional)
    volumes:
      - ../kong.yaml:/usr/local/kong/declarative/kong.yaml
    networks:
      - g-nexa-network

# ---------------------------------------
# 8. NETWORK & VOLUMES
# ---------------------------------------
networks:
  g-nexa-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  kafka_data:
    driver: local
  redis_data:
